units_type: character
feature_source: kaldi
feature_type: fbank
data:
    name: thchs30
    vocab: /home/oshindo/rnn-transducer/thchs30_label/thchs30_train_char_table.txt
    left_context_width: 3
    right_context_width: 0
    frame_rate: 30
    apply_cmvn: False
<<<<<<< HEAD
    max_input_length: 520
    max_target_length: 47
=======
    max_input_length: 521
    max_target_length: 94
>>>>>>> 5820314fd29b9289f0cecead60f180e2e64834ee
    batch_size: 3
    short_first: True
    shuffle: False
    train: /home/oshindo/kaldi/egs/thchs30/s5/data/fbank/train
    dev: /home/oshindo/kaldi/egs/thchs30/s5/data/fbank/dev
    test: /home/oshindo/kaldi/egs/thchs30/s5/data/fbank/test
model:
    type: transducer
    enc:
        type: attention
        d_inner: 512
        n_head: 16
        d_model: 320
        d_head: 20
        n_layer: 1
    dec:
        type: attention
<<<<<<< HEAD
        d_inner: 512
        n_head: 16
        d_model: 320
        d_head: 20
        n_layer: 1
    joint:
        input_size: 640
        inner_size: 512
    vocab_size: 2664
=======
        hidden_size:
        output_size:
        d_inner: 320
        n_head: 3
        d_model: 213
        d_head: 71
        n_layer: 1
    joint:
        input_size: 373
        inner_size: 512
    vocab_size: 213
>>>>>>> 5820314fd29b9289f0cecead60f180e2e64834ee
    share_weight: False
    feature_dim:
    dropout: 0.3
training:
    pre_train: False
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 2020
    num_gpu: 1
    epochs: 20
    max_grad_norm: 200
    visualization: True
    show_interval: 10
    save_model: word2vec_cooutput_abs_3lr_char
    save_pre_model: pre_encoder
optim:
    type: adam
    lr: 0.0001
    momentum: 0.9
    decay_ratio: 0.5
    weight_decay: 0
    begin_to_adjust_lr: 10
