units_type: character
feature_source: kaldi
feature_type: mfcc
data:
    name: timit
    vocab: /home/oshindo/kaldi/egs/timit/s5/data/lang/phones.txt
    left_context_width: 0
    right_context_width: 0
    frame_rate: 30
    apply_cmvn: False
    max_input_length: 1000
    max_target_length: 100
    batch_size: 8
    encoding: True
    short_first: True
    shuffle: False
    text_flag: text
    train: /home/oshindo/kaldi/egs/timit/s5/data/train
    dev: /home/oshindo/kaldi/egs/timit/s5/data/dev
    test: /home/oshindo/kaldi/egs/timit/s5/data/test
model:
    type: transducer
    enc:
        type: lstm
        hidden_size: 39
        output_size: 320
        n_layers: 3
        bidirectional: True
    dec:
        type: lstm
        hidden_size: 256
        output_size: 320
        n_layers: 1
    joint:
        input_size: 640
        inner_size: 512
    vocab_size: 49
    share_weight: False
    feature_dim: 39
    dropout: 0.3
    backend: c++
training:
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 2019
    num_gpu: 1
    epochs: 20
    max_grad_norm: 200
    visualization: True
    show_interval: 10
    save_model: 3blstm_128henc_1l256dec
optim:
    type: sgd
    lr: 0.0001
    momentum: 0.9
    decay_ratio: 0.5
    weight_decay: 0
    begin_to_adjust_lr: 10
